stages:
  - test
  - build

run_tests:
  stage: test
  image: node:9.11.1-alpine
  before_script:
    - npm install
  script: 
    - npm test

run_build:
  stage: build
  only:
    - master

  image: docker:stable
  
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  variables:
    DOCKER_DRIVER: overlay2
  
  services:
    - docker:dind

  script: 
    - docker build -t jamesvmcewan/mvl-app .
    - docker push jamesvmcewan/mvl-app