language: node_js
node_js:
  - 10.7.0
cache:
  directories:
    - node_modules

install:
  - yarn
script:
  - yarn workspace mvl-app lint
  - yarn workspace mvl-app test
  - yarn workspace mvl-app build --production
