# fly.toml app configuration file generated for mvl on 2025-04-16T16:40:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mvl'
primary_region = 'ams'

[build]

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
