/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst'
export {}
declare module 'sst' {
  export interface Resource {
    MarvelKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    PublicKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    'mvlapp-astro': {
      type: 'sst.aws.Astro'
      url: string
    }
  }
}
