name: Deploy
on:
  push:
    branches: deno2
  pull_request:
    branches: deno2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --allow-scripts=npm:sharp@0.33.5
      - run: deno lint
      - run: deno fmt --check
      - run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'mvl'
          entrypoint: 'server/entry.mjs'
          root: 'dist'
