name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.10.0
        uses: actions/setup-node@v1
        with:
          node-version: '15.10.0'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.10.0
        uses: actions/setup-node@v1
        with:
          node-version: '15.10.0'
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.10.0
        uses: actions/setup-node@v1
        with:
          node-version: '15.10.0'
      - run: npm ci --legacy-peer-deps
      - run: npm run test:CI
        env:
          CI: true
