name: Build and Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.5.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.5.0'
      - run: yarn install
      - name: Stash installed app
        uses: actions/upload-artifact@v1
        with:
          name: mvlApp
          path: /
        # - run: yarn lint
        # - run: yarn test:CI
        # - run: yarn build
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: unstash installed app
        uses: actions/download-artifact@v1
        with:
          name: mvlApp
      - run: ls -a
      - run: yarn build
