name: Build and Test

on: [push]

jobs:
  test-build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.5.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.5.0'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test:CI
        env:
          CI: true
