name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Bun latest
        uses: xhyrom/setup-bun@v0.1.6
        with:
          bun-version: latest
      - run: bun install
      - run: ENABLE_VC_BUILD=1 bun run build
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Bun latest
        uses: xhyrom/setup-bun@v0.1.6
        with:
          bun-version: latest
      - run: bun install
      - run: bun run lint
      - run: bun run format:check
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Bun latest
        uses: xhyrom/setup-bun@v0.1.6
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test
        env:
          CI: true
