name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - run: yarn install
      - run: yarn build
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - run: yarn install
      - run: yarn lint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - run: yarn install
      - run: yarn test:CI
        env:
          CI: true
